FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ./src/ ./src/
COPY ./TaskFlow.sln ./
RUN dotnet restore
RUN dotnet publish src/TaskFlow.NotificationsWorker/TaskFlow.NotificationsWorker.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish ./
ENTRYPOINT ["dotnet", "TaskFlow.NotificationsWorker.dll"]
